### ISSUE TITLE
The "extensions" option doesn't work

### ISSUE THREAD

**Issue by ozyman42** [feats/babel-plugin-inline-import#3]
OS: Windows 10
I'm running `npm run dev` from the command-line.

`package.json`:
```json
{
  ...
  "scripts": {
    "dev": "nodemon ./server.js --watch ./ --exec babel-node"
  },
  ...
}
```

`babel.rc`:
```json
{
  "presets": ["es2015"],
  "plugins": ["babel-plugin-inline-import", {
    "extensions": [".gql"]
  }]
}
```

Error:
```
...\node_modules\babel-core\lib\transformation\plugin.js:131
      throw new Error(messages.get("pluginInvalidProperty", loc, i, key));
      ^

Error: Plugin 1 specified in "...\\.babelrc" provided an invalid property of "extensions"
    at Plugin.init (...\node_modules\babel-core\lib\transformation\plugin.js:131:13)
    at Function.normalisePlugin (...\node_modules\babel-core\lib\transformation\file\options\option-manager.js:148:12)
    at ...\node_modules\babel-core\lib\transformation\file\options\option-manager.js:180:30
    at Array.map (native)
    at Function.normalisePlugins (...\node_modules\babel-core\lib\transformation\file\options\option-manager.js:154:20)
    at OptionManager.mergeOptions (...\node_modules\babel-core\lib\transformation\file\options\option-manager.js:229:36)
    at OptionManager.init (...\node_modules\babel-core\lib\transformation\file\options\option-manager.js:374:12)
    at compile (...\node_modules\babel-register\lib\node.js:103:45)
    at loader (...\node_modules\babel-register\lib\node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (...\node_modules\babel-register\lib\node.js:154:7) [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by fatfisz** [comment]
@AlexLeung You missed brackets:
```json
"plugins": [
  ["babel-plugin-inline-import", {
    "extensions": [".gql"]
  }]
]
```

Babel treated your original config as if it consisted of two plugins: `"babel-plugin-inline-import"` and `{"extensions": [".gql"]}`.

**Comment by ozyman42** [comment]
Ah okay.
